name: Run Monitor URL Saatlik

on:
  workflow_dispatch:  # Manuel çalıştırma
  schedule:
    - cron: "5 */3 * * *"  # Her 3 saatte bir çalışır

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ana_domain.py script
        run: |
          python ana_domain.py

      - name: Check if ana_link.txt is updated
        id: check_update
        run: |
          echo "Checking if ana_link.txt was updated:"
          cat ana_link.txt

          OLD_URL=$(cat ana_link.txt)
          NEW_URL=$(python ana_domain.py)

          if [ "$OLD_URL" == "$NEW_URL" ]; then
            echo "URL güncellemeye gerek yoktur"
            echo "no_update=true" >> $GITHUB_ENV
          else
            echo "$NEW_URL" > ana_link.txt
            echo "URL başarıyla ana_link.txt dosyasına güncellendi"
            echo "no_update=false" >> $GITHUB_ENV
          fi

      - name: Update m3u_link.txt with new domain + path
        run: |
          BASE_URL=$(cat ana_link.txt | sed 's:/*$::')  # sondaki / işareti temizlenir
          FULL_URL="$BASE_URL/tv/bein-sports-1/"
          echo "$FULL_URL" > m3u_link.txt

          echo "Yeni m3u_link.txt içeriği:"
          cat m3u_link.txt

      - name: Commit updated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add ana_link.txt m3u_link.txt
            if [ "${{ env.no_update }}" == "true" ]; then
              git commit -m "Domain URL güncellemeye gerek yoktur"
            else
              git commit -m "Domain URL ve m3u_link güncellendi"
            fi
            git push
          fi

      - name: Trigger m3u-link-saatlik.yml workflow
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/m3u-link-saatlik.yml/dispatches
