name: Merge M3U Playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir çalışır

jobs:
  merge-playlists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Run playlist merge script
      run: |
        python birlestir.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add playlist.m3u
        git commit -m "Update merged playlist [CI]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
