name: Run m3u_link.py script

on:
  workflow_run:
    workflows: ["Run link_alma.py script"]  # Ana Domain workflow'u tamamlandığında çalışacak
    types:
      - completed
 
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repository'yi Kopyala
        uses: actions/checkout@v4

      - name: 🛠️ Python ve Chrome Bağımlılıklarını Yükle
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager


      - name: Run m3u_link.py
        run: |
          python m3u_link.py

      # Ana link dosyasını kontrol ediyoruz
      - name: Check if m3u_link_alındı.txt is updated
        id: check_update
        run: |
          echo "Checking if m3u_link_alındı.txt was updated:"
          cat m3u_link_alındı.txt  # Dosyanın içeriğini kontrol ediyoruz
          
          OLD_URL=$(cat m3u_link_alındı.txt)
          NEW_URL=$(python m3u_link.py)  # Yeni URL'yi almak için scripti çalıştırıyoruz
          
          if [ "$OLD_URL" == "$NEW_URL" ]; then
            echo "URL güncellemeye gerek yoktur"
            echo "no_update=true" >> $GITHUB_ENV  # URL değişmemişse environment variable set ediyoruz
          else
            echo "URL başarıyla m3u_link_alındı.txt dosyasına güncellendi"
            echo "no_update=false" >> $GITHUB_ENV  # URL güncellenmişse farklı bir variable set ediyoruz
          fi

      # GitHub Actions'a yapılan değişiklikleri commit ediyoruz
      - name: Commit updated m3u_link_alındı.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Değişiklik olup olmadığını kontrol et
          git pull  # Güncel değişiklikleri almak için ekledik
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add m3u_link_alındı.txt
            if [ "${{ env.no_update }}" == "true" ]; then
              git commit -m "Son M3U linklerini güncellenmeye gerek yoktur"
            else
              git commit -m "Son M3U linkleri güncellendi."
            fi
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # kod-alma.yml workflow'unu tetiklemek
      - name: Trigger kod-alma.yml workflow
        if: ${{ success() }}  # Bu adımdan önce başarılı olursa tetiklenir
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/kod-alma.yml/dispatches
