name: Playlist Generator (15 dakikada bir)

on:
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir çalışır
  workflow_dispatch:

jobs:
  generate-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Public Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Clone Private Repository (Py)
      run: |
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py
        cd private_py
        git submodule deinit -f .
        git submodule update --init --recursive

    - name: Install Python dependencies
      run: |
        pip install requests 

    - name: Run birlestir.py
      run: python private_py/birlestir.py

    - name: Commit and push updated playlist.m3u
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add playlist.m3u
        git diff --cached --quiet || (git commit -m "Auto update playlist.m3u (15min)" && git push)
