name: Run Python Scripts from Private Repo - Saatlik

on:
  workflow_dispatch:          # Manuel tetikleme için
  schedule:
    - cron: '0 */3 * * *'     # Her 3 saatte bir çalıştırır

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Public Repository (veriler)
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Clone Private Repository (Py)
      run: |
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py
        cd private_py
        # Alt modül hatalarını engellemek için submodule'leri kontrol et ve temizle
        git submodule deinit -f .
        git submodule update --init --recursive

    - name: Install Python dependencies from private repo
      run: |
        pip install -r private_py/requirements.txt

    - name: Run ana_domain.py
      run: python private_py/ana_domain.py

    - name: Run link_alma.py
      run: python private_py/link_alma.py

    - name: Run m3u_link.py
      run: python private_py/m3u_link.py

    - name: Run kod_alma.py
      run: python private_py/kod_alma.py

    - name: Run link_hazırlama.py
      run: python private_py/link_hazırlama.py

    - name: Run encode.py
      run: python private_py/encode.py

    - name: Run verileri_birlestir.py
      run: python private_py/verileri_birlestir.py

    - name: Run txt_to_m3u.py
      run: python private_py/txt_to_m3u.py

    - name: Run birlestir.py
      run: python private_py/birlestir.py

    - name: Commit and push updated text files
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git diff --cached --quiet || (git commit -m "Update text files via workflow" && git push)
